# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2688b70194a9667f3141ac4bd1f703f9"
name = "rs-checkout-fields"
handle = "rs-checkout-fields"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_draft_orders,read_order_edits,read_orders,read_products,write_draft_orders,write_order_edits,write_orders,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
